package helper

const (
	Status          = "status"
	Err             = "error :"
	Msg             = "message :"
	ReqBdyErr       = "Error while parsing the request body:"
	InvalidEmailErr = "Invalid Email"
	HashErr         = "Error while hashing the password:"
	UserExistErr    = "user not exist:"
	CreateUserErr   = "Error while creating the new user :"
	FetchUserErr    = "Error while Fetching the user :"
	Res             = "Reponse"
	Fname           = "firstName"
	Lname           = "lastName"
	MobileNo        = "mobileNo"
	Email           = "email"
	PasswordErr     = "Password is not matching"
	Token           = "token"
	TokenErr        = "Token error"
	ValidatationErr = "Struct field validation error :"
	SignUpSuccess   = "signup successful!!!"
	UserExt         = "User already exist"
	Authorization   = "Authorization"
	ExpTime         = 24
	FindUserErr     = "Error while finding the user"
	Database        = "postgres"
	HostName        = "HOST"
	PortNum         = "PORT"
	DbUserName      = "USER"
	DbPassword      = "PASSWORD"
	DbName          = "DBNAME"
	DbSuccessMsg    = "Database connected successful"
)
